// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Comment struct {
	ID          int64     `json:"id"`
	PostID      int64     `json:"post_id"`
	Owner       string    `json:"owner"`
	ThreadOwner string    `json:"thread_owner"`
	CreatedAt   time.Time `json:"created_at"`
}

type Like struct {
	ID     int64  `json:"id"`
	PostID int64  `json:"post_id"`
	Owner  string `json:"owner"`
}

type Post struct {
	ID        int64     `json:"id"`
	Link      string    `json:"link"`
	Owner     string    `json:"owner"`
	Likes     int64     `json:"likes"`
	Comments  int64     `json:"comments"`
	Reposts   int64     `json:"reposts"`
	CreatedAt time.Time `json:"created_at"`
}
