// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type AllEdge struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type AllEdgesWeighted struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Weight int64     `json:"weight"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type AllNode struct {
	ID    int64     `json:"id"`
	Label string    `json:"label"`
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Comment struct {
	ID          int64     `json:"id"`
	PostID      int64     `json:"post_id"`
	Owner       string    `json:"owner"`
	ThreadOwner string    `json:"thread_owner"`
	CreatedAt   time.Time `json:"created_at"`
}

type CommentsEdge struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type CommentsEdgesWeighted struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Weight int64     `json:"weight"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type CommentsNode struct {
	ID    int64     `json:"id"`
	Label string    `json:"label"`
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Like struct {
	ID     int64  `json:"id"`
	PostID int64  `json:"post_id"`
	Owner  string `json:"owner"`
}

type LikesEdge struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type LikesEdgesWeighted struct {
	ID     int64     `json:"id"`
	Source int64     `json:"source"`
	Target int64     `json:"target"`
	Weight int64     `json:"weight"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type LikesNode struct {
	ID    int64     `json:"id"`
	Label string    `json:"label"`
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Post struct {
	ID        int64     `json:"id"`
	Link      string    `json:"link"`
	Owner     string    `json:"owner"`
	Likes     int64     `json:"likes"`
	Comments  int64     `json:"comments"`
	Reposts   int64     `json:"reposts"`
	CreatedAt time.Time `json:"created_at"`
}
